name: Detox e2e tests
on:
  push:
    branches: [main, master, testBranch]
  pull_request:
    branches: [main, master, testBranch]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install applesimutils manually
        run: |
          git clone https://github.com/wix/AppleSimulatorUtils.git
          cd AppleSimulatorUtils
          ./scripts/build.sh
          cd ..
      - name: Install Detox CLI
        run: npm install -g detox-cli
      - name: Build iOS App
        run: npx detox build --configuration ios.sim.release
      - name: Run Detox tests
        run: npx detox test --configuration ios.sim.release
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
