name: E2E (iOS)

on:
  push:
    branches: [main, master, testBranch]
  pull_request:
    branches: [master, main, testBranch]

jobs:
  build:
    name: E2E (iOS)
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Install Yarn Dependencies
        run: yarn install

      - name: Install Pod Dependencies
        run: cd ./ios && pod install && cd ..

      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Check and Install Xcode Command Line Tools
        run: |
          if ! xcode-select -p > /dev/null; then
            echo "Installing Xcode Command Line Tools..."
            xcode-select --install
          else
            echo "Xcode Command Line Tools already installed."
          fi

      - name: Install and Boot iPhone 15 Simulator
        run: |
          # Accept Xcode License (required in CI/CD environments)
          sudo xcodebuild -license accept

          # Install simulators (e.g., iPhone 15)
          xcrun simctl list devices
          xcrun simctl boot "iPhone 15"

          # Start the simulator (optional, you can also boot the simulator without this)
          open -a Simulator

      - name: Run Detox Build
        run: yarn test:build

      - name: Run Detox Test(s)
        run: |
          yarn start &

          METRO_BUNDLER_PID=$!

          yarn test:e2e

          DETOX_EXIT_CODE=$?

          kill $METRO_BUNDLER_PID

          exit $DETOX_EXIT_CODE
