name: Detox e2e tests
on:
  push:
    branches: [main, master, testBranch]
  pull_request:
    branches: [main, master, testBranch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install dependencies for iOS
        run: |
          brew install applesimutils
          npm install -g detox-cli
      # Build iOS app (Only once)
      - name: Build iOS App
        run: npx detox build --configuration ios.sim.release
      # Upload built .app as an artifact
      - name: Upload iOS app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ios/build/Build/Products/Release-iphonesimulator/MyApp.app

  test:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install dependencies for iOS
        run: |
          brew install applesimutils
          npm install -g detox-cli
      # Download the pre-built iOS app artifact
      - name: Download iOS app artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-app
      # Copy the .app file to the appropriate folder (if needed)
      - name: Copy .app to appropriate folder
        run: cp ios-app/MyApp.app ios/build/Build/Products/Release-iphonesimulator/
      # Run Detox tests using the pre-built app
      - name: Run detox tests
        run: npx detox test --configuration ios.sim.release
